<?php

namespace App\Http\Controllers\Auth;

use App\Auth\Md5CompatibleUserProvider;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Notifications\OtpNotification;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\RateLimiter;

class UnifiedLoginController extends Controller
{
    /**
     * Show the unified login form.
     */
    public function showLoginForm()
    {
        if (Auth::check()) {
            return redirect()->route('dashboard');
        }

        return view('auth.login');
    }

    /**
     * Step 1: Validate credentials via Ajax and send OTP.
     * Accepts email OR username as `identifier` (the legacy `email` field is also
     * still accepted for client-side back-compat — the front-end may still post it).
     */
    public function validateCredentials(Request $request): JsonResponse
    {
        // Front-end transitional: accept either `identifier` or legacy `email`.
        $identifier = trim((string) ($request->input('identifier') ?? $request->input('email') ?? ''));
        $request->merge(['identifier' => $identifier]);

        $request->validate([
            'identifier' => 'required|string|max:255',
            'password' => 'required|string',
        ]);

        // Rate limiting: 5 attempts per minute per IP
        $key = 'login-attempt:' . $request->ip();
        if (RateLimiter::tooManyAttempts($key, 5)) {
            $seconds = RateLimiter::availableIn($key);
            return response()->json([
                'success' => false,
                'message' => "Too many attempts. Please try again in {$seconds} seconds.",
            ], 429);
        }

        $field = filter_var($identifier, FILTER_VALIDATE_EMAIL) ? 'email' : 'username';

        $user = User::where($field, $identifier)
            ->where('status', 'active')
            ->first();

        if (!$user || !Md5CompatibleUserProvider::checkPassword($request->password, $user)) {
            RateLimiter::hit($key, 60);
            return response()->json([
                'success' => false,
                'message' => 'Invalid credentials.',
            ], 422);
        }

        // No real email → cannot deliver OTP. Log the user in directly with the
        // password they already verified above. Lower security, but the alternative
        // is a hard lockout for ~13k imported customers without an email on file.
        if (!$this->hasRealEmail($user)) {
            session()->forget(['otp_user_id', 'otp_remember']);
            RateLimiter::clear($key);

            Auth::login($user, $request->boolean('remember'));
            $request->session()->regenerate();

            return response()->json([
                'success' => true,
                'message' => 'Login successful.',
                'redirect' => $this->dashboardFor($user),
            ]);
        }

        // Generate 6-digit OTP
        $otp = str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);

        $user->update([
            'otp_code' => $otp,
            'otp_expires_at' => now()->addMinutes(5),
        ]);

        session(['otp_user_id' => $user->id, 'otp_remember' => $request->boolean('remember')]);

        try {
            $user->notify(new OtpNotification($otp));
        } catch (\Exception $e) {
            \Log::warning('OTP email failed: ' . $e->getMessage());
        }

        $parts = explode('@', $user->email);
        $name = $parts[0];
        $masked = substr($name, 0, 2) . str_repeat('*', max(strlen($name) - 4, 2)) . substr($name, -2) . '@' . $parts[1];

        return response()->json([
            'success' => true,
            'message' => 'OTP sent to your email.',
            'masked_email' => $masked,
            'otp_display' => in_array(config('mail.default'), ['log', 'array']) ? $otp : null,
        ]);
    }

    /**
     * A "real" email is one that's set and isn't the synthetic placeholder
     * generated by the WebLink importer for accounts that had no email upstream.
     */
    private function hasRealEmail(User $user): bool
    {
        return !empty($user->email) && !str_ends_with(strtolower($user->email), '@weblink.import');
    }

    /**
     * Resolve the dashboard route for a given user role.
     */
    private function dashboardFor(User $user): string
    {
        return match ($user->role) {
            'super_admin', 'admin' => route('admin.dashboard'),
            'recharge_admin' => route('recharge-admin.dashboard'),
            'reseller' => route('reseller.dashboard'),
            'client' => route('client.dashboard'),
            default => route('dashboard'),
        };
    }

    /**
     * Step 2: Verify OTP and complete login.
     */
    public function verifyOtp(Request $request): JsonResponse
    {
        $request->validate([
            'otp' => 'required|string|size:6',
        ]);

        $userId = session('otp_user_id');
        if (!$userId) {
            return response()->json([
                'success' => false,
                'message' => 'Session expired. Please login again.',
                'expired' => true,
            ], 422);
        }

        // Rate limiting
        $key = 'otp-verify:' . $userId;
        if (RateLimiter::tooManyAttempts($key, 5)) {
            $seconds = RateLimiter::availableIn($key);
            return response()->json([
                'success' => false,
                'message' => "Too many attempts. Please try again in {$seconds} seconds.",
            ], 429);
        }

        $user = User::find($userId);

        if (!$user || !$user->otp_code || $user->otp_code !== $request->otp) {
            RateLimiter::hit($key, 60);
            return response()->json([
                'success' => false,
                'message' => 'Invalid OTP code.',
            ], 422);
        }

        if ($user->otp_expires_at && $user->otp_expires_at->isPast()) {
            RateLimiter::hit($key, 60);
            return response()->json([
                'success' => false,
                'message' => 'OTP has expired. Please request a new one.',
            ], 422);
        }

        // Clear OTP
        $user->update([
            'otp_code' => null,
            'otp_expires_at' => null,
        ]);

        // Clear session data and rate limiters
        $remember = session('otp_remember', false);
        session()->forget(['otp_user_id', 'otp_remember']);
        RateLimiter::clear($key);
        RateLimiter::clear('login-attempt:' . $request->ip());

        Auth::login($user, $remember);
        $request->session()->regenerate();

        return response()->json([
            'success' => true,
            'message' => 'Login successful.',
            'redirect' => $this->dashboardFor($user),
        ]);
    }

    /**
     * Resend OTP.
     */
    public function resendOtp(Request $request): JsonResponse
    {
        $userId = session('otp_user_id');
        if (!$userId) {
            return response()->json([
                'success' => false,
                'message' => 'Session expired. Please login again.',
                'expired' => true,
            ], 422);
        }

        // Rate limiting: 3 resends per 5 minutes
        $key = 'otp-resend:' . $userId;
        if (RateLimiter::tooManyAttempts($key, 3)) {
            $seconds = RateLimiter::availableIn($key);
            return response()->json([
                'success' => false,
                'message' => "Please wait {$seconds} seconds before requesting another OTP.",
            ], 429);
        }

        $user = User::find($userId);
        if (!$user) {
            return response()->json([
                'success' => false,
                'message' => 'User not found.',
                'expired' => true,
            ], 422);
        }

        // Generate new OTP
        $otp = str_pad(random_int(0, 999999), 6, '0', STR_PAD_LEFT);

        $user->update([
            'otp_code' => $otp,
            'otp_expires_at' => now()->addMinutes(5),
        ]);

        RateLimiter::hit($key, 300);

        // Send OTP via email
        try {
            $user->notify(new OtpNotification($otp));
        } catch (\Exception $e) {
            \Log::warning('OTP email failed: ' . $e->getMessage());
        }

        return response()->json([
            'success' => true,
            'message' => 'New OTP sent to your email.',
            'otp_display' => in_array(config('mail.default'), ['log', 'array']) ? $otp : null,
        ]);
    }

    /**
     * Logout.
     */
    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login');
    }
}
