<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #333; }
        .header { border-bottom: 2px solid #4f46e5; padding-bottom: 15px; margin-bottom: 20px; }
        .header h1 { margin: 0; color: #4f46e5; font-size: 24px; }
        .header .company { font-size: 14px; color: #666; margin-top: 5px; }
        .meta-table { width: 100%; margin-bottom: 25px; }
        .meta-table td { padding: 4px 0; vertical-align: top; }
        .meta-table .label { color: #666; width: 120px; }
        .status { display: inline-block; padding: 2px 10px; border-radius: 4px; font-weight: bold; font-size: 11px; text-transform: uppercase; }
        .status-draft { background: #f3f4f6; color: #6b7280; }
        .status-issued { background: #dbeafe; color: #1d4ed8; }
        .status-paid { background: #dcfce7; color: #166534; }
        .status-overdue { background: #fee2e2; color: #991b1b; }
        .status-cancelled { background: #f3f4f6; color: #9ca3af; }
        .charges-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .charges-table th { background: #f9fafb; border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; color: #6b7280; }
        .charges-table td { border: 1px solid #e5e7eb; padding: 8px 12px; }
        .charges-table .amount { text-align: right; font-family: monospace; font-size: 13px; }
        .total-row td { font-weight: bold; background: #f9fafb; }
        .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #e5e7eb; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>INVOICE</h1>
        <div class="company">{{ config('app.name', 'rSwitch') }}</div>
    </div>

    <table class="meta-table">
        <tr>
            <td style="width: 50%;">
                <table>
                    <tr><td class="label">Invoice No:</td><td><strong>{{ $invoice->invoice_number }}</strong></td></tr>
                    <tr><td class="label">Date:</td><td>{{ $invoice->created_at->format('M j, Y') }}</td></tr>
                    <tr><td class="label">Due Date:</td><td>{{ $invoice->due_date->format('M j, Y') }}</td></tr>
                    <tr>
                        <td class="label">Status:</td>
                        <td><span class="status status-{{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span></td>
                    </tr>
                </table>
            </td>
            <td style="width: 50%;">
                <table>
                    <tr><td class="label">Bill To:</td><td><strong>{{ $invoice->user->name }}</strong></td></tr>
                    <tr><td class="label">Email:</td><td>{{ $invoice->user->email }}</td></tr>
                    <tr><td class="label">Period:</td><td>{{ $invoice->period_start->format('M j') }} – {{ $invoice->period_end->format('M j, Y') }}</td></tr>
                    <tr><td class="label">Currency:</td><td>{{ $invoice->user->currency ?? 'USD' }}</td></tr>
                </table>
            </td>
        </tr>
    </table>

    <table class="charges-table">
        <thead>
            <tr>
                <th>Description</th>
                <th style="width: 120px; text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Call Charges ({{ $invoice->period_start->format('M j') }} – {{ $invoice->period_end->format('M j, Y') }})</td>
                <td class="amount">{{ number_format((float) $invoice->call_charges, 4) }}</td>
            </tr>
            <tr>
                <td>DID / Number Charges</td>
                <td class="amount">{{ number_format((float) $invoice->did_charges, 4) }}</td>
            </tr>
            @if ((float) $invoice->tax_amount > 0)
            <tr>
                <td>Tax</td>
                <td class="amount">{{ number_format((float) $invoice->tax_amount, 4) }}</td>
            </tr>
            @endif
            <tr class="total-row">
                <td>Total Amount</td>
                <td class="amount">{{ number_format((float) $invoice->total_amount, 4) }}</td>
            </tr>
        </tbody>
    </table>

    @if ($invoice->paid_at)
        <p><strong>Paid on:</strong> {{ $invoice->paid_at->format('M j, Y \a\t H:i') }}</p>
    @endif

    <div class="footer">
        Generated by {{ config('app.name', 'rSwitch') }} on {{ now()->format('M j, Y H:i') }}
    </div>
</body>
</html>
