<?php

namespace App\Services;

use App\Models\Trunk;
use Illuminate\Support\Facades\Log;

class TrunkProvisioningService
{
    /**
     * Regenerate pjsip_trunks.conf from all active trunks and reload PJSIP.
     */
    public function provisionAll(): void
    {
        $content = $this->generateConfig();
        $this->writeConfig($content);

        try {
            $this->reloadPjsip();
        } catch (\Exception $e) {
            Log::warning('PJSIP reload failed after trunk provisioning', [
                'error' => $e->getMessage(),
            ]);
        }
    }

    /**
     * Generate the full pjsip_trunks.conf content from all active trunks.
     */
    public function generateConfig(): string
    {
        $trunks = Trunk::where('status', 'active')->orderBy('id')->get();

        $lines = [
            '; Auto-generated by rSwitch Laravel application',
            '; DO NOT EDIT MANUALLY -- changes will be overwritten',
            '; Generated: ' . now()->toDateTimeString(),
            '; Active trunks: ' . $trunks->count(),
            '',
        ];

        foreach ($trunks as $trunk) {
            $lines[] = $this->generateTrunkConfig($trunk);
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Generate PJSIP config sections for a single trunk.
     */
    protected function generateTrunkConfig(Trunk $trunk): string
    {
        $id = "trunk-{$trunk->direction}-{$trunk->id}";
        $isOutgoing = in_array($trunk->direction, ['outgoing', 'both']);
        $isIncoming = in_array($trunk->direction, ['incoming', 'both']);
        $hasAuth = !empty($trunk->username) && !empty($trunk->password);

        $sections = [];

        // --- Endpoint ---
        $ep = [
            "; --- Trunk: {$trunk->name} ({$trunk->provider}) [{$trunk->direction}] ---",
            "[{$id}]",
            "type=endpoint",
            "context={$trunk->incoming_context}",
            "transport=transport-{$trunk->transport}",
            "disallow=all",
            "allow={$trunk->codec_allow}",
            "direct_media=no",
            "rtp_symmetric=yes",
            "force_rport=yes",
            "rewrite_contact=yes",
        ];

        if ($hasAuth && $isOutgoing) {
            $ep[] = "outbound_auth={$id}-auth";
        }
        if ($isOutgoing) {
            $ep[] = "aors={$id}-aor";
        }

        $sections[] = implode("\n", $ep);

        // --- Auth (only if credentials set) ---
        if ($hasAuth) {
            $sections[] = implode("\n", [
                "[{$id}-auth]",
                "type=auth",
                "auth_type=userpass",
                "username={$trunk->username}",
                "password={$trunk->password}",
            ]);
        }

        // --- AOR (only for outgoing/both) ---
        if ($isOutgoing) {
            $port = $trunk->port ?: 5060;
            $sections[] = implode("\n", [
                "[{$id}-aor]",
                "type=aor",
                "contact=sip:{$trunk->host}:{$port}",
                "qualify_frequency=60",
            ]);
        }

        // --- Identify (match incoming packets from trunk host) ---
        $identify = [
            "[{$id}-identify]",
            "type=identify",
            "endpoint={$id}",
            "match={$trunk->host}",
        ];
        if (!empty($trunk->incoming_ip_acl)) {
            $ips = array_filter(array_map('trim', explode(',', $trunk->incoming_ip_acl)));
            foreach ($ips as $ip) {
                if ($ip !== $trunk->host) {
                    $identify[] = "match={$ip}";
                }
            }
        }
        $sections[] = implode("\n", $identify);

        // --- Registration (only if register=true and outgoing/both) ---
        if ($trunk->register && $isOutgoing && $hasAuth) {
            $reg = [
                "[{$id}-reg]",
                "type=registration",
                "outbound_auth={$id}-auth",
            ];

            if (!empty($trunk->register_string)) {
                $reg[] = "server_uri={$trunk->register_string}";
            } else {
                $reg[] = "server_uri=sip:{$trunk->host}";
                $reg[] = "client_uri=sip:{$trunk->username}@{$trunk->host}";
            }

            $reg[] = "retry_interval=60";
            $sections[] = implode("\n", $reg);
        }

        return implode("\n\n", $sections) . "\n";
    }

    /**
     * Write config content to the pjsip_trunks.conf file.
     */
    protected function writeConfig(string $content): void
    {
        $path = base_path('docker/asterisk/conf/pjsip_trunks.conf');
        file_put_contents($path, $content);
    }

    /**
     * Reload PJSIP in Asterisk via AMI (TCP socket).
     */
    protected function reloadPjsip(): bool
    {
        $host = config('services.ami.host', env('AMI_HOST', 'asterisk'));
        $port = (int) config('services.ami.port', env('AMI_PORT', 5038));
        $username = config('services.ami.username', env('AMI_USERNAME', 'laravel'));
        $secret = config('services.ami.secret', env('AMI_SECRET', ''));

        $fp = @fsockopen($host, $port, $errno, $errstr, 5);

        if (!$fp) {
            throw new \RuntimeException("AMI connection failed: {$errstr} ({$errno})");
        }

        // Read banner
        fgets($fp, 1024);

        // Login
        fwrite($fp, "Action: Login\r\nUsername: {$username}\r\nSecret: {$secret}\r\n\r\n");
        $loginResponse = $this->readAmiResponse($fp);

        if (stripos($loginResponse, 'Success') === false) {
            fclose($fp);
            throw new \RuntimeException('AMI login failed: ' . $loginResponse);
        }

        // Send pjsip reload command
        fwrite($fp, "Action: Command\r\nCommand: pjsip reload\r\n\r\n");
        $this->readAmiResponse($fp);

        // Logoff
        fwrite($fp, "Action: Logoff\r\n\r\n");
        fclose($fp);

        Log::info('PJSIP reloaded via AMI');

        return true;
    }

    /**
     * Read a complete AMI response (ends with double CRLF).
     */
    protected function readAmiResponse($fp): string
    {
        $response = '';
        $timeout = time() + 5;

        while (!feof($fp) && time() < $timeout) {
            $line = fgets($fp, 1024);
            if ($line === false) {
                break;
            }
            $response .= $line;
            if (trim($line) === '') {
                break;
            }
        }

        return $response;
    }
}
