[general]
enabled = yes
bindaddr = 0.0.0.0
port = 5038
webenabled = no

[laravel]
secret = rSwitch_AMI_s3cret_2024
deny = 0.0.0.0/0.0.0.0
permit = 172.16.0.0/255.240.0.0
permit = 10.0.0.0/255.0.0.0
permit = 192.168.0.0/255.255.0.0
read = command,system
write = command,system
